apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-developers
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany  # Alle Container im Pod haben Lese- und Schreibzugriff auf das Volume
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home  # Gemeinsamer Pfad auf dem Host, der die Home-Verzeichnisse der Entwickler enthält.
  #storageClassName: standard
