apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-developers
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce 
  #persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home  
  storageClassName: standard
